# Generated by Django 5.2.10 on 2026-02-17 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('last_practiced', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note_type', models.CharField(choices=[('notes', 'Notes'), ('roadmap', 'Roadmap'), ('reference', 'Reference')], max_length=20)),
                ('file', models.FileField(upload_to='note_library/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Skill_Tracker.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField()),
                ('daily_study_hours', models.PositiveIntegerField(blank=True, help_text='Hours per day you can study', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('roadmap', models.FileField(blank=True, null=True, upload_to='roadmaps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='Skill_Tracker.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('planned_time', models.PositiveIntegerField(default=0, help_text='daily_study time in hours')),
                ('actual_time', models.PositiveIntegerField(help_text='Actual study time in hours')),
                ('extra_time', models.PositiveIntegerField(default=0, help_text='Extra study time in hours')),
                ('project_done', models.BooleanField(default=False)),
                ('project_update', models.TextField(blank=True, null=True)),
                ('certification_done', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('topics_done', models.TextField(blank=True, null=True)),
                ('new_topic_done', models.BooleanField(default=False)),
                ('topic_notes', models.BooleanField(default=False)),
                ('notes_file', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_level', models.PositiveIntegerField(default=5, help_text='Confidence level from 1 to 10')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_or_points', models.TextField(blank=True, null=True)),
                ('marks_yourself', models.PositiveIntegerField(default=5, help_text='Rate yourself from 1 to 10')),
                ('is_completed', models.BooleanField(default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='Skill_Tracker.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
